#[derive(Debug)]
pub struct Instr(pub Op, pub Mode, pub Cycles);
impl Instr {
    pub fn from(opcode: u8) -> Instr {
        match opcode {
            0x00 => Instr(Op::Brk, Mode::Impl, Cycles::A(7)),
            0x01 => Instr(Op::Ora, Mode::IndX, Cycles::A(6)),
            0x05 => Instr(Op::Ora, Mode::Zero, Cycles::A(3)),
            0x06 => Instr(Op::Asl, Mode::Zero, Cycles::A(5)),
            0x08 => Instr(Op::Php, Mode::Impl, Cycles::A(3)),
            0x09 => Instr(Op::Ora, Mode::Imm, Cycles::A(2)),
            0x0a => Instr(Op::Asl, Mode::Acc, Cycles::A(2)),
            0x0d => Instr(Op::Ora, Mode::Abs, Cycles::A(4)),
            0x0e => Instr(Op::Asl, Mode::Abs, Cycles::A(6)),
            0x10 => Instr(Op::Bpl, Mode::Rel, Cycles::C(2)),
            0x11 => Instr(Op::Ora, Mode::IndY, Cycles::B(5)),
            0x15 => Instr(Op::Ora, Mode::ZeroX, Cycles::A(4)),
            0x16 => Instr(Op::Asl, Mode::ZeroX, Cycles::A(6)),
            0x18 => Instr(Op::Clc, Mode::Impl, Cycles::A(2)),
            0x19 => Instr(Op::Ora, Mode::AbsY, Cycles::B(4)),
            0x1d => Instr(Op::Ora, Mode::AbsX, Cycles::B(4)),
            0x1e => Instr(Op::Asl, Mode::AbsX, Cycles::A(7)),
            0x20 => Instr(Op::Jsr, Mode::Abs, Cycles::A(6)),
            0x21 => Instr(Op::And, Mode::IndX, Cycles::A(6)),
            0x24 => Instr(Op::Bit, Mode::Zero, Cycles::A(3)),
            0x25 => Instr(Op::And, Mode::Zero, Cycles::A(3)),
            0x26 => Instr(Op::Rol, Mode::Zero, Cycles::A(5)),
            0x28 => Instr(Op::Plp, Mode::Impl, Cycles::A(4)),
            0x29 => Instr(Op::And, Mode::Imm, Cycles::A(2)),
            0x2a => Instr(Op::Rol, Mode::Acc, Cycles::A(2)),
            0x2c => Instr(Op::Bit, Mode::Abs, Cycles::A(4)),
            0x2d => Instr(Op::And, Mode::Abs, Cycles::A(4)),
            0x2e => Instr(Op::Rol, Mode::Abs, Cycles::A(6)),
            0x30 => Instr(Op::Bmi, Mode::Rel, Cycles::C(2)),
            0x31 => Instr(Op::And, Mode::IndY, Cycles::B(5)),
            0x35 => Instr(Op::And, Mode::ZeroX, Cycles::A(4)),
            0x36 => Instr(Op::Rol, Mode::Zero, Cycles::A(5)),
            0x38 => Instr(Op::Sec, Mode::Impl, Cycles::A(2)),
            0x39 => Instr(Op::And, Mode::AbsY, Cycles::B(4)),
            0x3d => Instr(Op::And, Mode::AbsX, Cycles::B(4)),
            0x3e => Instr(Op::Rol, Mode::AbsX, Cycles::A(7)),
            0x40 => Instr(Op::Rti, Mode::Impl, Cycles::A(6)),
            0x41 => Instr(Op::Eor, Mode::IndX, Cycles::A(6)),
            0x45 => Instr(Op::Eor, Mode::Zero, Cycles::A(3)),
            0x46 => Instr(Op::Lsr, Mode::Zero, Cycles::A(5)),
            0x48 => Instr(Op::Pha, Mode::Impl, Cycles::A(3)),
            0x49 => Instr(Op::Eor, Mode::Imm, Cycles::A(2)),
            0x4a => Instr(Op::Lsr, Mode::Acc, Cycles::A(2)),
            0x4c => Instr(Op::Jmp, Mode::Abs, Cycles::A(3)),
            0x4d => Instr(Op::Eor, Mode::Abs, Cycles::A(4)),
            0x4e => Instr(Op::Lsr, Mode::Abs, Cycles::A(6)),
            0x50 => Instr(Op::Bvc, Mode::Rel, Cycles::C(2)),
            0x51 => Instr(Op::Eor, Mode::IndY, Cycles::B(5)),
            0x55 => Instr(Op::Eor, Mode::ZeroX, Cycles::A(4)),
            0x56 => Instr(Op::Lsr, Mode::ZeroX, Cycles::A(6)),
            0x58 => Instr(Op::Cli, Mode::Impl, Cycles::A(2)),
            0x59 => Instr(Op::Eor, Mode::AbsY, Cycles::B(4)),
            0x5d => Instr(Op::Eor, Mode::AbsX, Cycles::B(4)),
            0x5e => Instr(Op::Lsr, Mode::AbsX, Cycles::A(7)),
            0x60 => Instr(Op::Rts, Mode::Impl, Cycles::A(6)),
            0x61 => Instr(Op::Adc, Mode::IndX, Cycles::A(6)),
            0x65 => Instr(Op::Adc, Mode::Zero, Cycles::A(3)),
            0x66 => Instr(Op::Ror, Mode::Zero, Cycles::A(5)),
            0x68 => Instr(Op::Pla, Mode::Impl, Cycles::A(4)),
            0x69 => Instr(Op::Adc, Mode::Imm, Cycles::A(2)),
            0x6a => Instr(Op::Ror, Mode::Acc, Cycles::A(2)),
            0x6c => Instr(Op::Jmp, Mode::Ind, Cycles::A(5)),
            0x6d => Instr(Op::Adc, Mode::Abs, Cycles::A(4)),
            0x6e => Instr(Op::Ror, Mode::Abs, Cycles::A(6)),
            0x70 => Instr(Op::Bvs, Mode::Rel, Cycles::C(2)),
            0x71 => Instr(Op::Adc, Mode::IndY, Cycles::B(5)),
            0x75 => Instr(Op::Adc, Mode::ZeroX, Cycles::A(4)),
            0x76 => Instr(Op::Ror, Mode::ZeroX, Cycles::A(6)),
            0x78 => Instr(Op::Sei, Mode::Impl, Cycles::A(2)),
            0x79 => Instr(Op::Adc, Mode::AbsY, Cycles::B(4)),
            0x7d => Instr(Op::Adc, Mode::AbsX, Cycles::B(4)),
            0x7e => Instr(Op::Ror, Mode::AbsX, Cycles::A(7)),
            0x81 => Instr(Op::Sta, Mode::IndX, Cycles::A(6)),
            0x84 => Instr(Op::Sty, Mode::Zero, Cycles::A(3)),
            0x85 => Instr(Op::Sta, Mode::Zero, Cycles::A(3)),
            0x86 => Instr(Op::Stx, Mode::Zero, Cycles::A(3)),
            0x88 => Instr(Op::Dey, Mode::Impl, Cycles::A(2)),
            0x8a => Instr(Op::Txa, Mode::Impl, Cycles::A(2)),
            0x8c => Instr(Op::Sty, Mode::Abs, Cycles::A(4)),
            0x8d => Instr(Op::Sta, Mode::Abs, Cycles::A(4)),
            0x8e => Instr(Op::Stx, Mode::Abs, Cycles::A(4)),
            0x90 => Instr(Op::Bcc, Mode::Rel, Cycles::C(2)),
            0x91 => Instr(Op::Sta, Mode::IndY, Cycles::A(6)),
            0x94 => Instr(Op::Sty, Mode::ZeroX, Cycles::A(4)),
            0x95 => Instr(Op::Sta, Mode::ZeroX, Cycles::A(4)),
            0x96 => Instr(Op::Stx, Mode::ZeroY, Cycles::A(4)),
            0x98 => Instr(Op::Tya, Mode::Impl, Cycles::A(2)),
            0x99 => Instr(Op::Sta, Mode::AbsY, Cycles::A(5)),
            0x9a => Instr(Op::Txs, Mode::Impl, Cycles::A(2)),
            0x9d => Instr(Op::Sta, Mode::AbsX, Cycles::A(5)),
            0xa0 => Instr(Op::Ldy, Mode::Imm, Cycles::A(2)),
            0xa1 => Instr(Op::Lda, Mode::IndX, Cycles::A(6)),
            0xa2 => Instr(Op::Ldx, Mode::Imm, Cycles::A(2)),
            0xa4 => Instr(Op::Ldy, Mode::Zero, Cycles::A(3)),
            0xa5 => Instr(Op::Lda, Mode::Zero, Cycles::A(3)),
            0xa6 => Instr(Op::Ldx, Mode::Zero, Cycles::A(3)),
            0xa8 => Instr(Op::Tay, Mode::Impl, Cycles::A(2)),
            0xa9 => Instr(Op::Lda, Mode::Imm, Cycles::A(2)),
            0xaa => Instr(Op::Tax, Mode::Impl, Cycles::A(2)),
            0xac => Instr(Op::Ldy, Mode::Abs, Cycles::A(4)),
            0xad => Instr(Op::Lda, Mode::Abs, Cycles::A(4)),
            0xae => Instr(Op::Ldx, Mode::Abs, Cycles::A(4)),
            0xb0 => Instr(Op::Bcs, Mode::Rel, Cycles::C(2)),
            0xb1 => Instr(Op::Lda, Mode::IndY, Cycles::B(5)),
            0xb4 => Instr(Op::Ldy, Mode::ZeroX, Cycles::A(4)),
            0xb5 => Instr(Op::Lda, Mode::ZeroX, Cycles::A(4)),
            0xb6 => Instr(Op::Ldx, Mode::ZeroY, Cycles::A(4)),
            0xb8 => Instr(Op::Clv, Mode::Impl, Cycles::A(2)),
            0xb9 => Instr(Op::Lda, Mode::AbsY, Cycles::B(4)),
            0xba => Instr(Op::Tsx, Mode::Impl, Cycles::A(2)),
            0xbc => Instr(Op::Ldy, Mode::AbsX, Cycles::B(4)),
            0xbd => Instr(Op::Lda, Mode::AbsX, Cycles::B(4)),
            0xbe => Instr(Op::Ldx, Mode::AbsY, Cycles::B(4)),
            0xc0 => Instr(Op::Cpy, Mode::Imm, Cycles::A(2)),
            0xc1 => Instr(Op::Cmp, Mode::IndX, Cycles::A(6)),
            0xc4 => Instr(Op::Cpy, Mode::Zero, Cycles::A(3)),
            0xc5 => Instr(Op::Cmp, Mode::Zero, Cycles::A(3)),
            0xc6 => Instr(Op::Dec, Mode::Zero, Cycles::A(5)),
            0xc8 => Instr(Op::Iny, Mode::Impl, Cycles::A(2)),
            0xc9 => Instr(Op::Cmp, Mode::Imm, Cycles::A(2)),
            0xca => Instr(Op::Dex, Mode::Impl, Cycles::A(2)),
            0xcc => Instr(Op::Cpy, Mode::Abs, Cycles::A(4)),
            0xcd => Instr(Op::Cmp, Mode::Abs, Cycles::A(4)),
            0xce => Instr(Op::Dec, Mode::Abs, Cycles::A(3)),
            0xd0 => Instr(Op::Bne, Mode::Rel, Cycles::C(2)),
            0xd1 => Instr(Op::Cmp, Mode::IndY, Cycles::B(5)),
            0xd5 => Instr(Op::Cmp, Mode::ZeroX, Cycles::A(4)),
            0xd6 => Instr(Op::Dec, Mode::ZeroX, Cycles::A(6)),
            0xd8 => Instr(Op::Cld, Mode::Impl, Cycles::A(2)),
            0xd9 => Instr(Op::Cmp, Mode::AbsY, Cycles::B(4)),
            0xdd => Instr(Op::Cmp, Mode::AbsX, Cycles::B(4)),
            0xde => Instr(Op::Dec, Mode::AbsX, Cycles::A(7)),
            0xe0 => Instr(Op::Cpx, Mode::Imm, Cycles::A(2)),
            0xe1 => Instr(Op::Sbc, Mode::IndX, Cycles::A(6)),
            0xe4 => Instr(Op::Cpx, Mode::Zero, Cycles::A(3)),
            0xe5 => Instr(Op::Sbc, Mode::Zero, Cycles::A(3)),
            0xe6 => Instr(Op::Inc, Mode::Zero, Cycles::A(5)),
            0xe8 => Instr(Op::Inx, Mode::Impl, Cycles::A(2)),
            0xe9 => Instr(Op::Sbc, Mode::Imm, Cycles::A(2)),
            0xea => Instr(Op::Nop, Mode::Impl, Cycles::A(2)),
            0xec => Instr(Op::Cpx, Mode::Abs, Cycles::A(4)),
            0xed => Instr(Op::Sbc, Mode::Abs, Cycles::A(4)),
            0xee => Instr(Op::Inc, Mode::Abs, Cycles::A(6)),
            0xf0 => Instr(Op::Beq, Mode::Rel, Cycles::C(2)),
            0xf1 => Instr(Op::Sbc, Mode::IndY, Cycles::B(5)),
            0xf5 => Instr(Op::Sbc, Mode::ZeroX, Cycles::A(4)),
            0xf6 => Instr(Op::Inc, Mode::ZeroX, Cycles::A(6)),
            0xf8 => Instr(Op::Sed, Mode::Impl, Cycles::A(2)),
            0xf9 => Instr(Op::Sbc, Mode::AbsY, Cycles::B(4)),
            0xfd => Instr(Op::Sbc, Mode::AbsX, Cycles::B(4)),
            0xfe => Instr(Op::Inc, Mode::AbsX, Cycles::A(7)),
            other => Instr(Op::Illegal(other), Mode::Impl, Cycles::A(0)),
        }
    }
}

#[derive(Debug)]
pub enum Op {
    Adc,
    And,
    Asl,
    Bcc,
    Bcs,
    Beq,
    Bit,
    Bmi,
    Bne,
    Bpl,
    Brk,
    Bvc,
    Bvs,
    Clc,
    Cld,
    Cli,
    Clv,
    Cmp,
    Cpx,
    Cpy,
    Dec,
    Dex,
    Dey,
    Eor,
    Inc,
    Inx,
    Iny,
    Jmp,
    Jsr,
    Lda,
    Ldx,
    Ldy,
    Lsr,
    Nop,
    Ora,
    Pha,
    Php,
    Pla,
    Plp,
    Rol,
    Ror,
    Rti,
    Rts,
    Sbc,
    Sec,
    Sed,
    Sei,
    Slo,
    Sta,
    Stx,
    Sty,
    Stp,
    Tax,
    Tay,
    Tsx,
    Txa,
    Txs,
    Tya,
    Illegal(u8),
}

#[derive(Clone, Copy, Debug)]
pub enum Mode {
    Abs,
    AbsX,
    AbsY,
    Acc,
    Imm,
    Impl,
    Ind,
    IndX,
    IndY,
    Rel,
    Zero,
    ZeroX,
    ZeroY,
}
impl Mode {
    pub fn payload_len(self) -> u16 {
        match self {
            Mode::Abs => 2,
            Mode::AbsX => 2,
            Mode::AbsY => 2,
            Mode::Acc => 0,
            Mode::Imm => 1,
            Mode::Impl => 0,
            Mode::Ind => 1,
            Mode::IndX => 1,
            Mode::IndY => 1,
            Mode::Rel => 1,
            Mode::Zero => 1,
            Mode::ZeroX => 1,
            Mode::ZeroY => 1,
        }
    }
}

#[derive(Clone, Copy, Debug)]
pub enum Cycles {
    A(u8),
    B(u8), // +1 if page boundary crossed
    C(u8), // +1 if branch on same page; +2 if branch on different page
}
